### ISSUE TITLE
TS2309: An export assignment cannot be used in a module with other exported elements.

### ISSUE THREAD

**Issue by yoursunny** [alanshaw/it-pushable#8]
Since v1.4.1, TypeScript usage with in a module with `import` keyword is having TS2309 error.

**package.json**
```json
{
  "private": true,
  "dependencies": {
    "it-pushable": "^1.4.1",
    "typescript": "^4.1.3"
  }
}
```

**tsconfig.json**
```jsonc
{
  "compilerOptions": {
    "allowSyntheticDefaultImports": true,
    "moduleResolution": "node",
    "strict": true,
    "target": "ES2019"
  },
  "include": [
    "script.ts"
  ],
  "exclude": [
    "**/node_modules"
  ]
}
```

**script.ts**
```ts
import pushable from "it-pushable";

pushable();
```

**Compile command**
```bash
./node_modules/.bin/tsc
```

**Error message**
```text
node_modules/it-pushable/index.d.ts:24:1 - error TS2309: An export assignment cannot be used in a module with other exported elements.

24 export = pushable
   ~~~~~~~~~~~~~~~~~


Found 1 error.
```

**Comment by yoursunny** [comment]
This is a regression caused by #6 authored by @hugomrdias .

**Comment by hugomrdias** [comment]
err needs to be a namespace export ..... sorry, thats why you should never hand write type declarations.

**Comment by alanshaw** [comment]
Thanks for reporting @yoursunny and thanks for fixing @achingbrain. The fix been published as `v1.4.2`.
